name: "Hello World"
description: "Happy hacking Github action"
inputs:
  who-to-greet: #id
    description: "Who to greet"
    required: true
    default: 'World'
outputs:
  time: #id
    description: "The time we greeted you"

runs:
  using: "node12"
  main: "index.js"
