on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: TerryFunggg/play-with-github-action
      with:
        who-to-greet: 'Terry Funggg'

    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
